fak:	
	./wf augment fak-sitemap.xml fak-fakultaet-aktuelles.xml
	./wf augment fak-sitemap.xml fak-fakultaet-bericht.xml
	./wf augment fak-sitemap.xml fak-fakultaet-evaluation.xml
	./wf augment fak-sitemap.xml fak-fakultaet-fotos.xml
	./wf augment fak-sitemap.xml fak-fakultaet-kolloquium.xml
	./wf augment fak-sitemap.xml fak-fakultaet-konferenzen.xml
	./wf augment fak-sitemap.xml fak-fakultaet-mail.xml
	./wf augment fak-sitemap.xml fak-fakultaet-persverzeichnis.xml
	./wf augment fak-sitemap.xml fak-fakultaet-promhab.xml
	./wf augment fak-sitemap.xml fak-fakultaet-promverfahren.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-ecausstattung.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-ecbeleg.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-ecres.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-fakanleitung.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-fakbeleg.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume-fakres.xml
	./wf augment fak-sitemap.xml fak-fakultaet-raeume.xml
	./wf augment fak-sitemap.xml fak-fakultaet-stellen-mitarbeiter.xml
	./wf augment fak-sitemap.xml fak-fakultaet-stellen-professur.xml
	./wf augment fak-sitemap.xml fak-fakultaet-stellen.xml
	./wf augment fak-sitemap.xml fak-fakultaet-vergveranstaltungen.xml
	./wf augment fak-sitemap.xml fak-fakultaet-vortraege.xml
	./wf augment fak-sitemap.xml fak-fakultaet.xml
	./wf augment fak-sitemap.xml fak-forschung-berichte.xml
	./wf augment fak-sitemap.xml fak-forschung-infosys.xml
	./wf augment fak-sitemap.xml fak-forschung-wissen.xml
	./wf augment fak-sitemap.xml fak-forschung.xml
	./wf augment fak-sitemap.xml fak-start.xml
	./wf augment fak-sitemap.xml fak-studium-abamapo.xml
	./wf augment fak-sitemap.xml fak-studium-blog.xml
	./wf augment fak-sitemap.xml fak-studium-lsf.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-aenderungenModulhb.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-arbeit.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-ergaenzungen.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-fpo.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-modulhandbuch.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-praktika.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-seminare.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor-wahlpflicht.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-bachelor.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-aenderungenModulhb.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-arbeit.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-fpo.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-modulhandbuch.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-praktika.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-seminare.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-studienplan.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master-wahlpflicht.xml
	./wf augment fak-sitemap.xml fak-studium-studinf-master.xml
	./wf augment fak-sitemap.xml fak-studium-studinf.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-aenderung.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-arbeit.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-fortschritt.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-projektstudium.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-seminare.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-studplan07.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-studplan09.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba-wahlpflicht.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ba.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma-aenderung.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma-arbeit.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma-projekt.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma-seminare.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma-studplan.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf-ma.xml
	./wf augment fak-sitemap.xml fak-studium-studwinf.xml
	./wf augment fak-sitemap.xml fak-studium-stundenplaene.xml
	./wf augment fak-sitemap.xml fak-studium.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-inf-bc.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-inf-ma.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-inf.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-winf-bc.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-winf-ma.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910-winf.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere0910.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-inf-bc.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-inf-ma.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-inf.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-winf-bc.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-winf-ma.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011-winf.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen-weitere1011.xml
	./wf augment fak-sitemap.xml fak-veranstaltungen.xml
	./xslt-transform fak.xsl fak-fakultaet-aktuelles.xml
	./xslt-transform fak.xsl fak-fakultaet-bericht.xml
	./xslt-transform fak.xsl fak-fakultaet-evaluation.xml
	./xslt-transform fak.xsl fak-fakultaet-fotos.xml
	./xslt-transform fak.xsl fak-fakultaet-kolloquium.xml
	./xslt-transform fak.xsl fak-fakultaet-konferenzen.xml
	./xslt-transform fak.xsl fak-fakultaet-mail.xml
	./xslt-transform fak.xsl fak-fakultaet-persverzeichnis.xml
	./xslt-transform fak.xsl fak-fakultaet-promhab.xml
	./xslt-transform fak.xsl fak-fakultaet-promverfahren.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-ecausstattung.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-ecbeleg.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-ecres.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-fakanleitung.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-fakbeleg.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume-fakres.xml
	./xslt-transform fak.xsl fak-fakultaet-raeume.xml
	./xslt-transform fak.xsl fak-fakultaet-stellen-mitarbeiter.xml
	./xslt-transform fak.xsl fak-fakultaet-stellen-professur.xml
	./xslt-transform fak.xsl fak-fakultaet-stellen.xml
	./xslt-transform fak.xsl fak-fakultaet-vergveranstaltungen.xml
	./xslt-transform fak.xsl fak-fakultaet-vortraege.xml
	./xslt-transform fak.xsl fak-fakultaet.xml
	./xslt-transform fak.xsl fak-forschung-berichte.xml
	./xslt-transform fak.xsl fak-forschung-infosys.xml
	./xslt-transform fak.xsl fak-forschung-wissen.xml
	./xslt-transform fak.xsl fak-forschung.xml
	./xslt-transform fak.xsl fak-sitemap.xml
	./xslt-transform fak.xsl fak-start.xml
	./xslt-transform fak.xsl fak-studium-abamapo.xml
	./xslt-transform fak.xsl fak-studium-blog.xml
	./xslt-transform fak.xsl fak-studium-lsf.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-aenderungenModulhb.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-arbeit.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-ergaenzungen.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-fpo.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-modulhandbuch.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-praktika.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-seminare.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor-wahlpflicht.xml
	./xslt-transform fak.xsl fak-studium-studinf-bachelor.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-aenderungenModulhb.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-arbeit.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-fpo.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-modulhandbuch.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-praktika.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-seminare.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-studienplan.xml
	./xslt-transform fak.xsl fak-studium-studinf-master-wahlpflicht.xml
	./xslt-transform fak.xsl fak-studium-studinf-master.xml
	./xslt-transform fak.xsl fak-studium-studinf.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-aenderung.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-arbeit.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-fortschritt.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-projektstudium.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-seminare.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-studplan07.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-studplan09.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba-wahlpflicht.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ba.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma-aenderung.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma-arbeit.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma-projekt.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma-seminare.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma-studplan.xml
	./xslt-transform fak.xsl fak-studium-studwinf-ma.xml
	./xslt-transform fak.xsl fak-studium-studwinf.xml
	./xslt-transform fak.xsl fak-studium-stundenplaene.xml
	./xslt-transform fak.xsl fak-studium.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-inf-bc.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-inf-ma.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-inf.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-winf-bc.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-winf-ma.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910-winf.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere0910.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-inf-bc.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-inf-ma.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-inf.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-winf-bc.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-winf-ma.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011-winf.xml
	./xslt-transform fak.xsl fak-veranstaltungen-weitere1011.xml
	./xslt-transform fak.xsl fak-veranstaltungen.xml

clean:	
	rm -f *.html
